# -*- coding: utf-8 -*-
"""Consumo_de_Cerveja.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TAZUw4KhkP3QaSmC_sCoTzWT6U-QAx7N
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('consumo_cerveja.csv',sep=';')

df

df.shape

df.isna().any()

df.isna().sum()

df.head(8)

df.describe().round()