# -*- coding: utf-8 -*-
"""Matplotlib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x2DsPFtlKmy3aFUM3Sz5xPAO5lxZZep-
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# gráfico de barras
dados_x = np.linspace(0,10,10)
dados_y = dados_x * dados_x
figura = plt.figure()

#left,buttom,width,height
grafico = figura.add_axes([0,0,0.7,0.7])

rotulos = ['A','B','C','D', 'E', 'F', 'G', 'H', 'I', 'J']

grafico.bar(rotulos, dados_x)

grafico.bar(rotulos, dados_y, color = 'red')
figura

grafico.bar(rotulos, dados_x, color = 'red')
grafico.bar(rotulos, dados_y * 0.1, color = 'blue')
figura

x= [1,2,3,4,5]
y= [2,4,6,8,10]

plt.plot(x,y)
plt.xlabel ('eixo x')
plt.ylabel ('eixo y')
plt.title =('Gráfico de linhas')

x = np.random.rand(1000)
y = np.random.rand(1000)

plt.scatter(x,y, label = 'pontos aleatórios')
plt.xlabel ('eixo x')
plt.ylabel ('eixo y')
plt.title = 'Grafico de dispersão'
plt.legend()

labels = ['cat A', 'cat B', 'cat C']
sizes = [15,30,45]
plt.pie(sizes, labels=labels, autopct ='%1.1f%%')
plt.title = ('Gráfico de pizza')

x = np.linspace(0,10,100) #inicio, fim, numero de amostras
y = np.sin(x)
plt.plot(x,y)

dados = [1,2,2,3,3,3,4,4,5]

plt.hist(dados, bins=5, edgecolor = 'black')
plt.xlabel('Valores')
plt.ylabel('Frequencia')
plt.title = ('Gráfico de Histograma')

dados = [70,72,68,75,71,73,69,64]

plt.boxplot(dados)
plt.ylabel ('Valores')
plt.title =('Gráfico de Bloxplot')

dados_x = np.linspace(0,10,10)
dados_y = dados_x * dados_x

plt.figure(facecolor = 'white')
ax = plt.axes()
ax.set_facecolor('white')

plt.plot(dados_x,
         dados_y,
         color='red',
         linewidth= 2,
         markersize= 5,
         marker='o',
         linestyle='dashed',
         markeredgecolor='blue'
         )

plt.xlabel('eixo_x',
           fontweight='bold',
           fontsize = 'large',
           fontfamily = 'sans-serif',
           color='green',
          )
# Configuração do título
plt.title('Gráfico Simples',     # Texto do título
          fontweight='bold',     # Peso da fonte (negrito)
          fontsize='large',      # Tamanho da fonte
          color='blue'           # Cor da fonte
          )
# Adicionando a legenda
plt.legend(['Numeros aleatórios'],   # Texto da legenda
           loc='upper center',        # Posição da legenda (superior centro)
           bbox_to_anchor=(0.5, 1.0), # Posição do canto superior da legenda
           fontsize='large',          # Tamanho da fonte da legenda
           shadow=True,               # Sombra na legenda
           borderpad=1                # Espaçamento interno da legenda
          )

np.random.seed(42)

x = np.linspace(0,10,100) #cria cem valores igualmente espaçados

y1 = np.sin(x) + np.random.normal(0,0.2,len(x))
y2 = np.cos(x) + np.random.normal(0,0.2,len(x))
y3 = np.random.rand(len(x)) # len =  comprimento
y4 = 2 * x + np.random.normal(0,1,len(x))

plt.figure(facecolor='white', figsize=(12,8))

plt.subplot(2,2,1)
plt.plot(x, y1, color = 'blue')

plt.subplot(2,2,2)
plt.plot(x, y2, color = 'red')

plt.subplot(2,2,3)
plt.scatter(x, y3, color = 'green')

plt.subplot(2,2,4)
plt.plot(x, y4, color = 'purple')

plt.savefig('grafico1.png', dpi=300) # dpi = pontos por polegadas #savefig - salva figura

"""# Nova seção"""