# -*- coding: utf-8 -*-
"""Numpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CNwZ8TUri54te3CClM9hKEOSZP12T_Jj
"""

import numpy as np

lista=[0,1,2,3]
np.array(lista)

matriz = [[1,2,3,5,6,7,8,9]]

np.array(matriz)

from numpy.core.multiarray import arange
np.arange(0,11,2)

from numpy.core.multiarray import zeros
np.zeros((5,5))

from numpy.core.numeric import ones
np.ones((9,9))

np.eye((5))

np.random.rand(4)