# -*- coding: utf-8 -*-
"""Plotly_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ny_y3ERnOHNbc3dkeXibkTpGlDvqykAr
"""

import pandas as pd
import numpy as np
import plotly

import plotly.offline as py
import plotly. graph_objs as go
from plotly.offline import plot, iplot

import cufflinks as cf
cf.go_offline()
plotly.offline.init_notebook_mode(connected = True)

import plotly.io as pio
pio.renderers

pio.renderers.default = 'colab'

df = pd.DataFrame(np.random.randn(100,4),columns = 'A B C D'.split())

df.plot()

df.A.iplot(kind='bar')

df.sum().iplot(kind='bar')

df.iplot(kind='box')

df.iplot(kind='hist', bins=())

df.iplot(kind='bubble', x='A', y='B', size = 'C',columns= 'seagreen')