# -*- coding: utf-8 -*-
"""Python_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14nQ9dnIIybgDjma8SYhUUCKlODW3mpJA

##Tipos de dados

###Númericos
"""

1+1

1*3

1/2

2**4

4%2

(2+3)*(5+5)

type(1)

type(1.2)

type("Teste")

"""##Definição de váriavel"""

nome_variavel = 2

nome_variavel

print(nome_variavel)

x=2
y=3

z=x+y

z

"""##Strings"""

'citação simples'

"citação dupla"

x = 'olá'

x

type(x)

anos = 42
nome = "Alice"
print(f"Meu nome é {nome} e eu tenho {anos} anos.")

"""##Listas"""

[1,2,3]

['oi',1,[1,2]]

minha_lista = ['a','b','c']

minha_lista.append('d')

minha_lista

minha_lista[1]

minha_lista[2]

minha_lista[1]='t'

minha_lista

len(minha_lista)

minha_lista[1:]

minha_lista[:1]

minha_lista[0]= 'novo'

minha_lista

minha_lista.insert(1,22)

minha_lista

minha_lista[0] = 'new'

minha_lista

minha_lista_2 = [1,2,3, [4,5,['target']]]

minha_lista_2

minha_lista_2[3]

minha_lista_2[3][2]

minha_lista_2[3][2][0]

minha_lista_3=[0,1,2,3,4,5,6,7,8,9]

sublista = minha_lista_3[2:5]

sublista

sublista = minha_lista_3[1:8:2]

sublista

reverso = minha_lista_3[::-1]

reverso

minha_lista_3[-1]

"""##Dicionario"""

meu_dicio = {
    "nome" : "Alice",
    "idade": 42,
    "cidade": "Sampa"
}

meu_dicio['nome']

meu_dicio['cidade']

meu_dicio['idade']

meu_dicio["profissão"]="Engenheira"

meu_dicio

"""##Booleanos"""

True

False

(1 > 2)

(1 >= 1)

(1 <= 4)

(1 == 1)

x=1

x !=1

"""##Operadores Lógicos"""

(1 > 2) and (2 < 3)

(1 > 2) or (2 < 3)

"""##Operadores condicionais

### if, else, elif
"""

if 1 < 2 :
  print("Sim")

if 1 < 2 :
  print("Brincar")
else:
  print("Apanhar")

if 2 < 2 :
  print("Brincar")
elif 3 > 4 :
  print("Apanhar")
else:
  print("Dorme")

"""##Loops

###For While
"""

cesta = ["maça", "banana", "manga"]

for fruta in cesta :
  print(fruta)

seq = [1,2,3,4,5]

for x in seq:
  print(x)

for y in seq:
  print(y + y)

for y in seq:
  print(y * y)

for y in seq:
  print(y - y)

contador = 1
while contador <= 5 :
  print(contador)
  contador += 1

contador = 1
while contador <= 8 :
  print(contador)
  contador += 1

"""#Range"""

range(5)

for x in range(5):
  print(x)

list(range(5))

"""##Funções"""

def nome_da_funcao(parametro1, parametro2):
  print("Ação da Função")

def minha_funcao(parametro):
  potencia = parametro ** 2
  return potencia

minha_funcao(2)

minha_funcao(25)

parametro = 4

resposta = minha_funcao(parametro)

resposta

minha_funcao(4)

