# -*- coding: utf-8 -*-
"""Titanic_Análise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KjVo78qiA1-RjqyMgZ4wVZIoDUDlk0ka
"""

import pandas as pd #para se trabalhar com dados relacionais (ou rotulados)
import numpy as np #funções p/ se trabalhar com computação numérica. Seu principal objeto é o vetor n-dimensional, ou ndarray . Um vetor n-dimensional também é conhecido pelo nome tensor
import seaborn as sns #para plotagem dos mais variados tipos de gráficos
import matplotlib.pyplot as plt #oferece recursos de plotagem para a criação de gráficos 2D e 3D com visualizações estáticas, animadas e interativas.

df = pd.read_csv('titanic_train.csv')#csv =  arquivo em formato de tabela, comando read para ler o arquivo.

df # chamando o arquivo para visualização

df.head(10) #O método head() lê as primeiras linhas do seu DataFrame.

df.info() # conferir cada tipo de dado, O método info() é útil para obtenção de uma rápida descrição dos dados, como total de linhas, número de colunas, tipo de cada série e se há valores nulos

df.describe().round(2) # mostra estatísticas descritivas, como média, desvio padrão, máximo, mínimo e outras tendências centrais, além da forma da distribuição. funçãoi round arrendo números

df.corr().round(4) #corr() é usado para encontrar a correlação de pares de todas as colunas no dataframe.